/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libmansystem.Views;

import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 *
 * @author Ibrahim-Abdullah
 */
public class BooksAvailableTable extends javax.swing.JFrame {

    /**
     * Creates new form BooksAvailableTable
     */
    public BooksAvailableTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Books = new javax.swing.JMenu();
        AddBook = new javax.swing.JMenuItem();
        RemoveBook = new javax.swing.JMenuItem();
        UpdateBook = new javax.swing.JMenuItem();
        SearchBook = new javax.swing.JMenuItem();
        BorrowBook = new javax.swing.JMenuItem();
        ReturnBook = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ViewAllBooks = new javax.swing.JMenuItem();
        ViewBorrowedBooks = new javax.swing.JMenuItem();
        ViewAvailableBooks = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        author = new javax.swing.JMenuItem();
        title = new javax.swing.JMenuItem();
        publisher = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Available Books");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("LIST FOR ALL AVAILABLE BOOKS");

        Books.setMnemonic('B');
        Books.setText("Books");

        AddBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AddBook.setMnemonic('A');
        AddBook.setText("Add Books");
        Books.add(AddBook);

        RemoveBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        RemoveBook.setMnemonic('R');
        RemoveBook.setText("Remove Book");
        Books.add(RemoveBook);

        UpdateBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        UpdateBook.setMnemonic('U');
        UpdateBook.setText("Update Book");
        Books.add(UpdateBook);

        SearchBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SearchBook.setMnemonic('c');
        SearchBook.setText("Search");
        Books.add(SearchBook);

        BorrowBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        BorrowBook.setMnemonic('o');
        BorrowBook.setText("Borrow Book");
        Books.add(BorrowBook);

        ReturnBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ReturnBook.setMnemonic('t');
        ReturnBook.setText("Return Book");
        Books.add(ReturnBook);

        jMenuBar1.add(Books);

        jMenu2.setMnemonic('V');
        jMenu2.setText("View");

        ViewAllBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ViewAllBooks.setMnemonic('l');
        ViewAllBooks.setText("All Books");
        ViewAllBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllBooksActionPerformed(evt);
            }
        });
        jMenu2.add(ViewAllBooks);

        ViewBorrowedBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ViewBorrowedBooks.setMnemonic('r');
        ViewBorrowedBooks.setText("Borrow Books");
        jMenu2.add(ViewBorrowedBooks);

        ViewAvailableBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ViewAvailableBooks.setMnemonic('v');
        ViewAvailableBooks.setText("Availble Books");
        jMenu2.add(ViewAvailableBooks);

        jMenuBar1.add(jMenu2);

        jMenu1.setMnemonic('S');
        jMenu1.setText("Search By");

        author.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        author.setMnemonic('u');
        author.setText("Author");
        jMenu1.add(author);

        title.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        title.setMnemonic('T');
        title.setText("Title");
        jMenu1.add(title);

        publisher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        publisher.setMnemonic('P');
        publisher.setText("Publisher");
        jMenu1.add(publisher);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAllBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewAllBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksAvailableTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksAvailableTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksAvailableTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksAvailableTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BooksAvailableTable().setVisible(true);
            }
        });
    }
    public JMenuItem getAddBooksMenuItem(){
        return AddBook;
    }
    public JMenuItem getBorrowBooksMenuItem(){
        return this.BorrowBook;
    }
    public JMenuItem getRemoveBookMenuItem(){
        return this.RemoveBook;
    }
    public JMenuItem getReturnBookMenuItem(){
        return this.ReturnBook;
    }
    public JMenuItem getSearchBookMenuItem(){
        return this.SearchBook;
    }
    public JMenuItem getUpdateBookMenuItem(){
        return this.UpdateBook;
    }
    public JMenuItem getAuthorMenuItem(){
        return this.author;
    }
   public JMenuItem getTitleMenuItem(){
        return this.title;
    }
    public JMenuItem getPublisherMenuItem(){
        return this.publisher;
    }
    public JMenuItem getViewAvailableBooksMenuItem(){
        return this.ViewAvailableBooks;
    }
    public JMenuItem getViewAllBooksMenuItem(){
        return this.ViewAllBooks;
    }
    public JMenuItem getViewBorrwedBooksMenuItem(){
        return this.ViewBorrowedBooks;
    }
    
//    public JButton getAddButton(){
//        return btnAddBook;
//    }
//    public JButton getEditButton(){
//        return btnEditBook;
//    }
//    public JButton getDeleteButton(){
//        return btnDeleteBook;
//    }
//    public JButton getSearchButton(){
//        return btnSearchBook;
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddBook;
    private javax.swing.JMenu Books;
    private javax.swing.JMenuItem BorrowBook;
    private javax.swing.JMenuItem RemoveBook;
    private javax.swing.JMenuItem ReturnBook;
    private javax.swing.JMenuItem SearchBook;
    private javax.swing.JMenuItem UpdateBook;
    private javax.swing.JMenuItem ViewAllBooks;
    private javax.swing.JMenuItem ViewAvailableBooks;
    private javax.swing.JMenuItem ViewBorrowedBooks;
    private javax.swing.JMenuItem author;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem publisher;
    private javax.swing.JMenuItem title;
    // End of variables declaration//GEN-END:variables
}
